import React,{useMemo,useState}from"react";import{createRoot}from"react-dom/client";import"./styles.css";
const brands=[{name:"Nike",note:"Public disclosures on supplier standards, labour conditions and supply-chain governance."},{name:"adidas",note:"Public reporting covering human rights, supplier due diligence and grievance mechanisms."},{name:"ASICS",note:"Public reporting and supplier standards covering labour, human rights and environmental topics."}];
const products=[{id:1,brand:"Nike",name:"Air Zoom Pegasus",cat:"Running",price:"NZ$189",buy:"https://www.nike.com/nz/",img:"https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80"},{id:2,brand:"adidas",name:"Ultraboost",cat:"Running",price:"NZ$240",buy:"https://www.adidas.co.nz/",img:"https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=900&q=80"},{id:3,brand:"ASICS",name:"GEL-KAYANO",cat:"Running",price:"NZ$220",buy:"https://www.asics.com/nz/en-nz/",img:"https://images.unsplash.com/photo-1460353581641-37baddab0fa2?auto=format&fit=crop&w=900&q=80"}];
const evidence=[{brand:"Nike",topic:"Labour",title:"Supplier standards and labour due diligence",detail:"Nike publishes information about supplier standards, supply-chain governance and worker-related risks.",source:"Nike sustainability reporting",url:"https://www.nike.com/sustainability"},{brand:"adidas",topic:"Labour",title:"Human rights and supply-chain due diligence",detail:"adidas reports on human-rights due diligence, supplier monitoring and grievance mechanisms.",source:"adidas sustainability reporting",url:"https://www.adidas-group.com/en/sustainability/"},{brand:"ASICS",topic:"Supply Chain",title:"Supplier standards",detail:"ASICS publishes supplier requirements addressing labour and human-rights topics.",source:"ASICS sustainability reporting",url:"https://corp.asics.com/en/csr"}];
function App(){const[v,setV]=useState("home"),[q,setQ]=useState(""),[sel,setSel]=useState(null);const res=useMemo(()=>products.filter(p=>!q||[p.name,p.brand,p.cat].join(" ").toLowerCase().includes(q.toLowerCase())),[q]);const product=p=>{setSel(p);setV("product")};return <><header><div className="nav"><button className="logo"onClick={()=>setV("home")}>TRUECHOICE<span>™</span></button><nav><button onClick={()=>setV("shop")}>Shop</button><button onClick={()=>setV("brands")}>Brands</button><button onClick={()=>setV("evidence")}>Evidence</button><button onClick={()=>setV("how")}>How it works</button></nav><div className="search"><input value={q}onChange={e=>setQ(e.target.value)}placeholder="Search products or brands"/><button onClick={()=>setV("shop")}>Search</button></div></div></header>
{v==="home"&&<main><section className="hero"><div><p className="eyebrow">EVIDENCE BEFORE OPINION</p><h1>Shop what<br/><em>you believe in.</em></h1><p className="lead">Understand the companies behind the products you buy — using evidence, sources and dates so you can make your own choice.</p><button className="primary"onClick={()=>setV("shop")}>Explore products →</button></div><div className="heroCard"><b>TC</b><p>Company information<br/>Product information<br/>Evidence & sources<br/>Purchase options</p></div></section><section className="section"><h2>Featured products</h2><div className="grid">{products.map(p=><Card p={p}go={product}key={p.id}/>)}</div></section></main>}
{v==="shop"&&<main className="page"><h1>Find a product</h1><p>Search the catalogue and open the evidence behind each company.</p><div className="searchBig"><input value={q}onChange={e=>setQ(e.target.value)}placeholder="Try Nike, running shoes, adidas..."/><span>{res.length} products</span></div><div className="grid">{res.map(p=><Card p={p}go={product}key={p.id}/>)}</div></main>}
{v==="brands"&&<main className="page"><h1>Companies</h1><p>Explore what each company publicly says and the evidence recorded.</p><div className="brands">{brands.map(b=><button className="brand"onClick={()=>{setSel(b);setV("brand")}}key={b.name}><i>{b.name[0]}</i><div><h3>{b.name}</h3><p>{b.note}</p></div>→</button>)}</div></main>}
{v==="product"&&sel&&<main className="page"><button className="back"onClick={()=>setV("shop")}>← Back</button><div className="detail"><img src={sel.img}/><div><p className="eyebrow">{sel.brand}</p><h1>{sel.name}</h1><h2>{sel.price}</h2><p>Product information is separated from company evidence so you can see both the item and the organisation behind it.</p><div className="chips"><span>Labour</span><span>Supply chain</span><span>Environment</span><span>Transparency</span></div><button className="primary"onClick={()=>window.open(sel.buy,"_blank")}>Buy from brand →</button><button className="secondary"onClick={()=>{setSel(brands.find(b=>b.name===sel.brand));setV("brand")}}>View company evidence</button></div></div></main>}
{v==="brand"&&sel&&<main className="page"><button className="back"onClick={()=>setV("brands")}>← Back</button><div className="company"><i>{sel.name[0]}</i><div><p className="eyebrow">COMPANY PROFILE</p><h1>{sel.name}</h1><p>{sel.note}</p></div></div><div className="evidence">{evidence.filter(e=>e.brand===sel.name).map((e,i)=><Evidence e={e}key={i}/>)}</div><button className="secondary"onClick={()=>setV("evidence")}>Open Evidence Explorer →</button></main>}
{v==="evidence"&&<main className="page"><h1>Evidence Explorer</h1><p>See the source, not just the label. Missing evidence is not treated as proof of wrongdoing.</p><div className="evidence">{evidence.map((e,i)=><Evidence e={e}key={i}/>)}</div></main>}
{v==="how"&&<main className="page"><h1>Evidence before opinion.</h1><div className="steps">{[["01","Find","Search for a product or company."],["02","Explore","See labour, supply chain, environment and transparency topics."],["03","Verify","Open the underlying source and check its date and type."],["04","Choose","Use the information to make your own purchasing decision."]].map(s=><div className="step"><b>{s[0]}</b><h2>{s[1]}</h2><p>{s[2]}</p></div>)}</div></main>}
<footer><b>TRUECHOICE™</b><span>Prototype MVP · Evidence-led shopping</span></footer></>}
function Card({p,go}){return <button className="card"onClick={()=>go(p)}><img src={p.img}/><div><small>{p.brand}</small><h3>{p.name}</h3><p>{p.cat}</p><strong>{p.price}</strong></div></button>}function Evidence({e}){return <article className="ev"><small>{e.topic} · Company disclosure</small><h3>{e.title}</h3><p>{e.detail}</p><span>{e.source}</span><a href={e.url}target="_blank">Open source ↗</a></article>}createRoot(document.getElementById("root")).render(<App/>);